# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    command: npm start
    volumes:
      - ./../../ExpressApp:/opt/projects/DockerExpressMongo/ExressApp/
      # - /opt/projects/DockerExpressMongo/ExressApp/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    mongo:
      image: mongo
    ports:
      — "27017:27017"
  #   volumes_from:
  #     - mongodata
  # mongodata:
  #   image: tianon/true
  #   volumes:
  #     - /data/db
  #   command: echo "Data container for express mongo DB."